[project]
name = "yth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopandas>=1.1.1",
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.8",
    "rasterio>=1.4.4",
    "scikit-learn>=1.8.0",
]
